import Profile from "../../components/Profile.jsx"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div >
      <Profile />
      {children}
    </div>
  )
}
