import Navbar from "./components/Navbar.jsx"
import "../globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
